{"name": "user tries to log in with different failing credentials -- @1.2 ", "status": "passed", "steps": [{"name": "Given I go to start page", "status": "passed", "start": 1609114828479, "stop": 1609114830671}, {"name": "When I click log in button", "status": "passed", "start": 1609114830671, "stop": 1609114832707}, {"name": "When I put my email \"FakeUser2\" and password \"<password>\"", "status": "passed", "start": 1609114832711, "stop": 1609114832843}, {"name": "And I confirm the log in", "status": "passed", "start": 1609114832843, "stop": 1609114835089}, {"name": "Then wrong email or password shows up", "status": "passed", "start": 1609114835089, "stop": 1609114835128}, {"name": "And close browser", "status": "passed", "start": 1609114835128, "stop": 1609114836349}], "parameters": [{"name": "username", "value": "FakeUser2"}, {"name": "passwor", "value": "FakePasswor"}], "start": 1609114819972, "stop": 1609114836349, "uuid": "026c2d4f-e784-4eae-a466-c318a0352930", "historyId": "0307e6cea5b31b18cd219a5a528d1872", "fullName": "features/login.feature:user tries to log in with different failing credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User logs"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}