{"name": "user tries to log in with different failing credentials -- @1.2 ", "status": "passed", "steps": [{"name": "Given I go to start page", "status": "passed", "start": 1609116294867, "stop": 1609116296998}, {"name": "When I click log in button", "status": "passed", "start": 1609116296998, "stop": 1609116298848}, {"name": "When I put my email \"FakeUser2\" and password \"<password>\"", "status": "passed", "start": 1609116298848, "stop": 1609116298964}, {"name": "And I confirm the log in", "status": "passed", "start": 1609116298964, "stop": 1609116301209}, {"name": "Then wrong email or password shows up", "status": "passed", "start": 1609116301210, "stop": 1609116301247}, {"name": "And close browser", "status": "passed", "start": 1609116301247, "stop": 1609116302582}], "parameters": [{"name": "username", "value": "FakeUser2"}, {"name": "passwor", "value": "FakePasswor"}], "start": 1609116286380, "stop": 1609116302582, "uuid": "93b7bd6d-fe0e-43dd-94b9-71c21579f4ca", "historyId": "0307e6cea5b31b18cd219a5a528d1872", "fullName": "features/login.feature:user tries to log in with different failing credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User logs"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}