{"name": "user tries to log in with different failing credentials -- @1.1 ", "status": "passed", "steps": [{"name": "Given I go to start page", "status": "passed", "start": 1609116278103, "stop": 1609116280696}, {"name": "When I click log in button", "status": "passed", "start": 1609116280696, "stop": 1609116282698}, {"name": "When I put my email \"FakeUser\" and password \"<password>\"", "status": "passed", "start": 1609116282702, "stop": 1609116282806}, {"name": "And I confirm the log in", "status": "passed", "start": 1609116282810, "stop": 1609116285060}, {"name": "Then wrong email or password shows up", "status": "passed", "start": 1609116285060, "stop": 1609116285092}, {"name": "And close browser", "status": "passed", "start": 1609116285092, "stop": 1609116286376}], "parameters": [{"name": "username", "value": "FakeUser"}, {"name": "passwor", "value": "FakePasswor"}], "start": 1609116269605, "stop": 1609116286376, "uuid": "e41aa816-ac73-4268-b91c-58f1b4809fb2", "historyId": "e508437f2f7dc6a46b1e0650052843ed", "fullName": "features/login.feature:user tries to log in with different failing credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User logs"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}